export const contact = {
  title: "Pedí tu presupuesto: quince minutos, gratis | Luvant",
  description:
    "Contanos qué hacés todos los días a mano. Salís sabiendo si se puede, cuánto sale y cuánto tarda.",
  path: "/contacto",
  updatedAt: "2026-09-13",
  eyebrow: "Tu caso",
  h1: "¿Qué es lo que hacés todos los días ",
  h1Accent: "a mano?",
  intro:
    "Contalo con tus palabras, como se lo contarías a alguien en el mostrador. Con eso alcanza para decirte si se puede y cuánto sale.",
  steps: [
    { label: "Primero", title: "Te escribimos", text: "por correo para coordinar la llamada." },
    { label: "Después", title: "Hablamos", text: "de lo que hacés a mano, qué usás hoy y adónde tendría que ir." },
    {
      label: "Al colgar",
      title: "Sabés si se puede, cuánto sale y cuánto tarda.",
      text: "Y si no te conviene, te lo decimos ahí mismo.",
    },
  ],
  direct: "¿Preferís escribir directo?",
  form: {
    tab: "Formulario",
    tabRight: "Pedí tu presupuesto",
    topics: [
      { id: "software", label: "Software a medida" },
      { id: "ia", label: "Automatización con IA" },
      { id: "datos", label: "Datos y tableros" },
      { id: "integracion", label: "Integración" },
      { id: "web", label: "Web y apps" },
      { id: "lens", label: "Luvant Lens" },
      { id: "nose", label: "No sé todavía" },
    ],
    topicLabel: "Sobre qué",
    caseLabel: "Qué hacés a mano hoy",
    casePlaceholder: 'Ej.: "Me llegan unas 200 facturas por mes por correo y las cargo una por una en Tango."',
    nameLabel: "Tu nombre",
    namePlaceholder: "Nombre y, si querés, el negocio",
    emailLabel: "Tu correo",
    emailPlaceholder: "nombre@empresa.com",
    submit: "Pedí tu presupuesto",
    note: ["Sin compromiso.", "No mandamos publicidad."],
    error: "Hubo un error al enviar. Probá de nuevo en un momento.",
  },
  thanks: {
    title: "Recibimos tu pedido | Luvant",
    eyebrow: "Después de mandar",
    h2: "Listo. Te escribimos para coordinar.",
    text: "Mientras tanto, si tenés un ejemplo a mano (una factura, un mensaje de pedido, una planilla), guardalo: en la llamada lo miramos juntos.",
    received: "Recibido",
    about: "Sobre",
    next: "Próximo paso",
    nextValue: "coordinar quince minutos",
  },
};
